### ISSUE TITLE
Undefined is not a function in Good Module

### ISSUE THREAD

**Issue by program247365** [krakenjs/kappa#107]
On node: v0.12.2

Commands I run:
npm init {follow instructions}
npm install kappa --save
npm start

```
$ npm start
> my-kappa@0.0.1 start /home/kridgway/kappa
> kappa -c config.json

/home/kridgway/kappa/node_modules/good/lib/index.js:12
    server.on('stop', function () {
           ^
TypeError: undefined is not a function
    at exports.register (/home/kridgway/kappa/node_modules/good/lib/index.js:12:12)
    at /home/kridgway/kappa/node_modules/kappa/node_modules/hapi/lib/plugin.js:187:23
    at iterate (/home/kridgway/kappa/node_modules/kappa/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at Object.exports.serial (/home/kridgway/kappa/node_modules/kappa/node_modules/hapi/node_modules/items/lib/index.js:38:9)
    at internals.Plugin.register (/home/kridgway/kappa/node_modules/kappa/node_modules/hapi/lib/plugin.js:171:11)
    at /home/kridgway/kappa/node_modules/kappa/node_modules/hapi/node_modules/glue/lib/index.js:188:22
    at iterate (/home/kridgway/kappa/node_modules/kappa/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at Object.exports.serial (/home/kridgway/kappa/node_modules/kappa/node_modules/hapi/node_modules/items/lib/index.js:38:9)
    at /home/kridgway/kappa/node_modules/kappa/node_modules/hapi/node_modules/glue/lib/index.js:185:19
    at iterate (/home/kridgway/kappa/node_modules/kappa/node_modules/hapi/node_modules/items/lib/index.js:35:13)
```
    
My package.json:
   
```
{
  "name": "my-kappa",
  "version": "0.0.1",
  "description": "My Installation of Kappa, an NPM Proxy.\"",
  "main": "index.js",
  "dependencies": {
    "good": "^6.1.2",
    "good-console": "^5.0.0",
    "hapi": "^8.4.0",
    "kappa": "^1.0.0-rc.11"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "kappa -c config.json"
  },
  "author": "",
  "license": "ISC"
}    
```

Does Kappa work on the latest Hapi/Good versions?  In the interim, does anybody know what exact versions of the modules work to run Kappa?

**Comment by jasisk** [comment]
Currently, we support the following versions:
``` json
{
    "good": "^3",
    "good-console": "^2",
    "hapi": "^7"
}
```

**Comment by program247365** [comment]
Thanks! Putting in those versions made it all work. :+1: 

Look how excited I am!

![too-excited](https://cloud.githubusercontent.com/assets/13910/7501098/d3150448-f3ff-11e4-9f5b-b6f830d9533f.gif)

**Comment by jasisk** [comment]
You're excited? **I'M EXCITED!**

![too excited](https://cloud.githubusercontent.com/assets/62923/7501788/c3d3c6ae-f404-11e4-9614-479deeb21a28.GIF)

**Comment by program247365** [comment]
:laughing:
